spring:
#  sleuth:
#    sampler:
#      percentage:  1
  zipkin:
    baseUrl: localhost:9411
  cloud:
    stream:
      bindings:
        output:
            destination:  networkChangeTopic
            content-type: application/json
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost

eureka:
  instance:
    preferIpAddress: true
    ipAddress: 172.20.0.7
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    sjph.life.friendship: DEBUG

#security:
#  oauth2:
#    resource:
#       userInfoUri: http://localhost:8901/auth/user