version: '3'
services:
  lifeeurekaserver:
    image: sjphichina/life-service-eureka:0.7
    ports:
      - "8761:8761"
    networks:
      - app
  lifecassandra:
#    image: cassandra/life:latest
    image: cassandra:latest
    ports:
      - "9042:9042"
    networks:
      - db_cassandra
  liferedis:
#   image: redis:alpine
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - cache_redis
  lifeconfsvr:
    image: sjphichina/confsvr:life
    ports:
      - "9888:9888"
    depends_on:
      - "lifeeurekaserver"
    environment:
      EUREKASERVER_URI: "http://lifeeurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    networks:
      - app
  lifeconfsvr2:
    image: sjphichina/confsvr:life
    ports:
      - "9889:9889"
    depends_on:
      - "lifeeurekaserver"
    environment:
      EUREKASERVER_URI: "http://lifeeurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    networks:
      - app
  lifefriendship:
    image: sjphichina/friendship:life
    ports:
      - "9080:9080"
    depends_on:
      - "lifeeurekaserver"
      - "lifeconfsvr"
      - "lifecassandra"
      - "liferedis"
    environment:
      PROFILE: "default"
      SERVER_PORT: "9080"
      EUREKASERVER_URI: "http://lifeeurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_URI: "http://lifeconfsvr:9888"
      CONFIGSERVER_PORT:   "9888"
      DB_CASSANDRA_PORT: "9042"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    networks:
      - app
      - db_cassandra
      - cache_redis
  lifefriendship2:
    image: sjphichina/friendship:life
    ports:
      - "9081:9081"
    depends_on:
      - "lifeeurekaserver"
      - "lifeconfsvr"
      - "lifecassandra"
      - "liferedis"
    environment:
      PROFILE: "default"
      SERVER_PORT: "9081"
      EUREKASERVER_URI: "http://lifeeurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_URI: "http://lifeconfsvr:9888"
      CONFIGSERVER_PORT:   "9888"
      DB_CASSANDRA_PORT: "9042"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    networks:
      - app
      - db_cassandra
      - cache_redis
  lifefriendship3:
    image: sjphichina/friendship:life
    ports:
      - "9082:9082"
    depends_on:
      - "lifeeurekaserver"
      - "lifeconfsvr"
      - "lifecassandra"
      - "liferedis"
    environment:
      PROFILE: "default"
      SERVER_PORT: "9082"
      EUREKASERVER_URI: "http://lifeeurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_URI: "http://lifeconfsvr:9888"
      CONFIGSERVER_PORT:   "9888"
      DB_CASSANDRA_PORT: "9042"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    networks:
      - app
      - db_cassandra
      - cache_redis
networks:
  db_cassandra:
  cache_redis:
  app:

