version: '3'
services:
  lifeeurekaserver:
    image: sjphichina/life-util-eureka:0.7
    ports:
      - "8761:8761"
    networks:
      - app
  lifeconfsvr:
    image: sjphichina/life-util-confsvr:0.7
    ports:
      - "9888:9888"
    environment:
      EUREKASERVER_URI: "http://lifeeurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    networks:
      - app
  lifezipkin:
    image: sjphichina/life-util-zipkin:0.7
    ports:
      - "9411:9411"
    environment:
      ZIPKIN_URI: "http://lifezipkin:9411"
      SERVER_PORT: "9411"
    networks:
      - app
  liferedis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - app
  lifekafka:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
    networks:
      - app
  lifeelasticsearch:
    image: elasticsearch:2.4.6
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elasticsearch
  lifezuul:
    image: sjphichina/life-util-zuul:0.7
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://lifeconfsvr:9888"
      EUREKASERVER_URI: "http://lifeeurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      CONFIGSERVER_PORT:   "9888"
      ZIPKIN_URI: "http://lifezipkin:9411"
      ZIPKIN_PORT:         "9411"
    networks:
      - app
  lifeauthentication:
    image: sjphichina/life-service-authentication:0.7
    ports:
      - "8901:8901"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8901"
      DATABASE_PORT:     3306
      CONFIGSERVER_PORT: 9888
      EUREKASERVER_PORT: 8761
      CONFIGSERVER_URI: "http://lifeconfsvr:9888"
      EUREKASERVER_URI: "http://lifeeurekaserver:8761/eureka/"
      ZIPKIN_URI: "http://lifezipkin:9411"
      ZIPKIN_PORT:         "9411"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    networks:
      - app
  lifeuser:
    image: sjphichina/life-service-user:0.7
    ports:
      - "9090:9090"
    environment:
      PROFILE: "aws"
      SERVER_PORT: "9090"
      EUREKASERVER_URI: "http://lifeeurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_URI: "http://lifeconfsvr:9888"
      CONFIGSERVER_PORT:   "9888"
      DB_MYSQL_PORT: "3306"
      REDIS_PORT:          "6379"
      KAFKASERVER_URI: "lifekafka"
      ZKSERVER_URI: "lifekafka"
      KAFKASERVER_PORT:    "2181"
      ZIPKIN_URI: "http://lifezipkin:9411"
      ZIPKIN_PORT:         "9411"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    networks:
      - app
  lifepost:
    image: sjphichina/life-service-post:0.7
    ports:
      - "9070:9070"
    environment:
      PROFILE: "aws"
      SERVER_PORT: "9070"
      EUREKASERVER_URI: "http://lifeeurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_URI: "http://lifeconfsvr:9888"
      CONFIGSERVER_PORT:   "9888"
      ZIPKIN_URI: "http://lifezipkin:9411"
      ZIPKIN_PORT:         "9411"
      DB_MYSQL_PORT: "3306"
      REDIS_PORT:          "6379"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    networks:
      - app
      - elasticsearch
  lifewebstie:
    image: sjphichina/life-app-website:0.7
    ports:
      - "80:80"
    environment:
      PROFILE: "default"
      SERVER_PORT: "80"
      CONFIGSERVER_PORT: 9888
      CONFIGSERVER_URI: "http://lifeconfsvr:9888"
      EUREKASERVER_PORT: 8761
      EUREKASERVER_URI: "http://lifeeurekaserver:8761/eureka/"
      ZIPKIN_URI: "http://lifezipkin:9411"
      ZIPKIN_PORT:         "9411"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    networks:
      - app
      - elasticsearch
  lifeshorturl:
    image: sjphichina/life-service-shorturl:0.7
    ports:
      - "9060:9060"
    environment:
      PROFILE: "aws"
      SERVER_PORT: "9060"
      EUREKASERVER_URI: "http://lifeeurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_URI: "http://lifeconfsvr:9888"
      CONFIGSERVER_PORT:   "9888"
      ZIPKIN_URI: "http://lifezipkin:9411"
      ZIPKIN_PORT:         "9411"
      DB_MYSQL_PORT: "3306"
      REDIS_PORT:          "6379"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    networks:
      - app
volumes:
  esdata1:
    driver: local
networks:
  elasticsearch:
  app:

