version: '3'
services:
  lifemysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - db_mysql
networks:
  db_mysql:
  db_cassandra:
  cache_redis:
  message_kafka:
  app:

