#Setting the logging levels for the service
logging:
  level:
    org.springframework: WARN
    sjph.life.shorturl: WARN

spring:
  zipkin:
    baseUrl: localhost:9411

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
