security:
  oauth2:
    resource:
       userInfoUri: http://localhost:8901/auth/user

spring:
#  sleuth:
#    sampler:
#      percentage:  1
  zipkin:
    baseUrl: localhost:9411
eureka:
  instance:
    preferIpAddress: true
    #ipAddress: 172.20.0.6
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

      
#Setting logging levels
logging:
  level:
    org.springframework: WARN
    sjph.life.post: INFO