#Setting the logging levels for the service
logging:
  level:
    org.springframework: WARN
    sjph.life: WARN

eureka:
  instance:
    preferIpAddress: true
    #ipAddress: 172.19.0.4
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

server:
  contextPath:   /auth