example.property: "I AM IN THE DEFAULT from Github"
#Cassandra
database.ip: "172.18.0.2"
database.port: "9042"
database.keyspace: "life_user"
spring.jpa.database: "CASSANDRA"
spring.datasource.platform:  "cassandra"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "com.dbschema.CassandraJdbcDriver"
spring.datasource.url: "jdbc:cassandra://localhost:9042/life_user"
spring.datasource.username: ""
spring.datasource.password: ""
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.CassandraSQLDialect"

#Redis
redis.server: "redis"
redis.ip: "172.20.0.2"
redis.port: "6379"
signing.key: "345345fsdfsf5345"